title: "LDEO-pCO2 HPD Back in Time"
description: >
  The ocean reduces human impact on the climate by absorbing and sequestering CO2 .
  From 1950s to the 1980s, observations of pCO2 and related ocean carbon variables were sparse and uncertain.
  Thus, global ocean biogeochemical models (GOBMs) have been the basis for quantifying the ocean carbon sink.
  The LDEO-Hybrid Physics Data product (LDEO-HPD) interpolates sparse surface ocean pCO2 data to global coverage
  by using GOBMs as priors, and applying machine learning to estimate full-coverage corrections.
recipes:
  - id: "GCB-2023_dataprod_LDEO-HPD_1959-2022-updated-flipped-lon"
    object: "recipe:flux"
  - id: "annual-sfco2"
    object: "recipe:annual_sfco2"
provenance:
  providers:
    - name: "LDEO"
      description: "Lamont Doherty Earth Observatory at Columbia"
      roles:
        - producer
        - licensor
    - name: "LEAP"
      description: "STC: Center for Learning the Earth with Artificial Intelligence and Physics"
      roles:
        - producer
        - licensor
  license: "CC BY"
maintainers:
  - name: "Anderson Banihirwe"
    github: andersy005
