name: catalog

on:
  pull_request:
    branches:
  push:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: validate feedstock entry
        uses: leap-stc/data-catalog-actions/leap-catalog@main
        with:
          single-feedstock: "./feedstock/catalog.yaml"

      - name: Dispatch event
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_USER_TOKEN }}
          script: |
            await github.repos.createDispatchEvent({
              owner: 'leap-stc',
              repo: 'data-management',
              event_type: 'update-catalog',
              client_payload: {
                origin_repo: `${context.repo.owner}/${context.repo.repo}`
              }
            })
